#include <stdio.h>
#include <errno.h>
#include <stdlib.h>

#define OUTPUT(statement) printf("%s%s\n", loop, statement)
#define OUTPUT_NOTAB(statement) printf("%s\n", statement)

int main(int argc, char** argv) {
	FILE* input = stdin;

	if (argc > 1) input = fopen(argv[1], "r");
	if (input == NULL) {
		fprintf(stderr, "%s: error: %m\n", argv[0]);
		return 50 + (errno % 20);
	}

	/* stores tab characters */
	char loop[8];
	for (int i = 1; i < 8; i++) loop[i] = 0;
	loop[0] = '\t';

	char current;
	OUTPUT_NOTAB("/* generated by bran */");
	OUTPUT_NOTAB("#include <stdio.h>");
	OUTPUT_NOTAB("");
	OUTPUT_NOTAB("char buffer[1024];");
	OUTPUT_NOTAB("");
	OUTPUT_NOTAB("int main(void)");
	OUTPUT_NOTAB("{");
	OUTPUT("register unsigned int offset = 0;");

	while ((current = fgetc(input)) != EOF) {
		switch (current) {
			case '>':
				OUTPUT("offset++;");
				break;
			case '<':
				OUTPUT("offset--;");
				break;
			case '+':
				OUTPUT("buffer[offset]++;");
				break;
			case '-':
				OUTPUT("buffer[offset]--;");
				break;
			case '.':
				OUTPUT("printf(\"\%c\", buffer[offset]);");
				break;
			case ',':
				OUTPUT("buffer[offset] = getchar();");
				break;
			case '[':
				OUTPUT("while (buffer[offset] != 0)");
				OUTPUT("{");
				for (int i = 0; i < 8; i++)
					if (loop[i] != '\t' && (loop[i] = '\t'))
						break;
				break;
			case ']':
				for (int i = 7; i --> 0;)
					if (loop[i] == '\t' && (loop[i] = 0) == 0)
						break;
				OUTPUT("} /* end while */");
				break;
		}
	}

	OUTPUT_NOTAB("\treturn 0;");
	OUTPUT_NOTAB("}");
	OUTPUT_NOTAB("/* eof */");

	return EXIT_SUCCESS;
}
