#include <stdio.h>
#include <errno.h>
#include <stdlib.h>

int main(int argc, char** argv) {
	FILE* input = stdin;

	if (argc > 1) input = fopen(argv[1], "r");
	if (input == NULL) {
		fprintf(stderr, "%s: error: %m\n", argv[0]);
		return 50 + (errno % 20);
	}

	char current;
	printf(	";; generated by bran\n"
		"	bits 64\n"
		"	section .data\n"
		"buffer: times 1024 db 0\n"
		"\n	section .text\n"
		"	global _start\n"
		"_start:\tmov r8, buffer\n"
		"	xor r9,r9\n");

	char looptbl[255];
	for (int i = 0; i <= 255; i++) looptbl[i] = 0;
	int currentLoop = 0;

	while ((current = fgetc(input)) != EOF) {
		switch (current) {
			case '>':
				puts("\tinc r9");
				break;
			case '<':
				puts("\tdec r9");
				break;
			case '+':
				puts("\tinc byte [r8 + r9]");
				break;
			case '-':
				puts("\tdec byte [r8 + r9]");
				break;
			case '.':
				puts(		"\txor r10,r10\n"
						"\tmov r10,r9\n"
						"\tadd r10,r8\n"
						"\tmov rax,1\n"
						"\tmov rdi,0\n"
						"\tmov rsi,r10\n"
						"\tmov rdx,1\n"
						"\tpush r8\n"
						"\tpush r9\n"
						"\tsyscall\n"
						"\tpop r9\n"
						"\tpop r8");
				break;
			case ',':
				puts(		"\txor r10,r10\n"
						"\tmov r10,r9\n"
						"\tadd r10,r8\n"
						"\txor rax,rax\n"
						"\tmov rbx,1\n"
						"\tmov rcx,r10\n"
						"\tmov rdx,1\n"
						"\tpush r9\n"
						"\tpush r8\n"
						"\tsyscall\n"
						"\tpop r8\n"
						"\tpop r9");
				break;
			case '[':
				for (int i = 1; i <= 255; i++)
					if (looptbl[i] == 0) {
						currentLoop = i;
						looptbl[i] = 1;
						break;
					}

				printf("Lb%d:\tcmp byte [r8 + r9],0\n"
						"\tje Le%d\n",
						currentLoop, currentLoop);
				break;
			case ']':
				for (int i = 255; i >= 0; i--)
					if (looptbl[i] == 1) {
						currentLoop = i;
						looptbl[i] = 2;
						break;
					}
				printf("Le%d:\tcmp byte [r8 + r9],0\n"
						"\tjne Lb%d\n",
						currentLoop, currentLoop);
				break;
		}
	}

	printf("\tmov eax,60\n"
			"\txor ebx, ebx\n"
			"\tsyscall\n"
			"; EOF\n");
}
